# Generated by Django 6.0.3 on 2026-03-30 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='criteria_scores',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='feedback',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
