# Generated by Django 5.2.1 on 2026-03-30 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluator', '0002_submission_criteria_scores_alter_submission_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='student_answer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('is_correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='evaluator.question')),
            ],
        ),
        migrations.AddField(
            model_name='submission',
            name='selected_choice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='evaluator.choice'),
        ),
    ]
