# Generated by Django 5.2.1 on 2026-03-30 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluator', '0003_alter_submission_student_answer_choice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='raw_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
