# Generated by Django 6.0.3 on 2026-04-06 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluator', '0004_submission_raw_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='time_limit',
            field=models.IntegerField(default=5, help_text='Time limit in minutes'),
        ),
    ]
